trigger: none 
pool: Default

stages:
- stage: Build_Stage
  displayName: Build Stage
  jobs:
  - job: Build_Job
    displayName: Build Job
    steps:
    - task: NodeTool@0
      displayName: NodeInstall
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
    - task: Npm@1
      displayName: NPM Install
      inputs:
        command: 'install'
        workingDir: '$(Build.SourcesDirectory)'
    - task: Npm@1
      displayName: NPM Build
      inputs:
        command: 'custom'
        workingDir: '$(Build.SourcesDirectory)'
        customCommand: 'run build'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/Build'
        artifact: 'todo-ui'
        publishLocation: 'pipeline'

- stage: Deploy_Stage
  displayName: Deploy Stage
  jobs:
  - job: Deploy_Job
    displayName: Deploy Job
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'todo-ui'
        targetPath: '$(Agent.BuildDirectory)'