name: todo-ui-pipeline
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: workflow_dispatch
jobs:
  Build:
    name: buildjob
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1
    - name: print a greeting
      run: echo "hello world"
